---
- hosts: solr
  roles:
    - ten7.flightdeck_base
  tasks:
    - name: Install from apk.
      apk:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - "openjdk7-jre"
        - "curl"
        - "tar"
        - "rsync"
      notify:
        - clear apk cache
    - name: Create a temp directory to store files needed by the run
      tempfile:
        state: directory
        prefix: "ansible-deploy-"
      register: _run_temp_dir
      notify:
        - delete temp items
    - name: Download solr
      get_url:
        url: "https://archive.apache.org/dist/lucene/solr/5.5.5/solr-5.5.5.tgz"
        dest: "{{ _run_temp_dir.path }}/solr.tar.gz"
        checksum: "sha1:d88bac37bec50f13c1d41f1ff569df457e8a7d47"
        mode: "u=rwx,g=rwx,o="
    - name: Ensure key directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: "solr"
        group: "solr"
        mode: "u=rwx,g=rwx,o=r"
        recurse: yes
      loop:
        - "/opt"
        - "/data"
        - "{{ _run_temp_dir.path }}/solr"
        - "{{ _run_temp_dir.path }}/search_api_solr"
        - "{{ _run_temp_dir.path }}/apachesolr"
    - name: Expand archive
      unarchive:
        src: "{{ _run_temp_dir.path }}/solr.tar.gz"
        dest: "{{ _run_temp_dir.path }}/solr"
        owner: "solr"
        group: "solr"
        mode: "u=rwx,g=rwx,o=r"
        extra_opts:
          - "--strip-components=1"
    - name: Move the solr directory to /opt
      command: >
        mv {{ _run_temp_dir.path }}/solr /opt/
    - name: Remove unnecessary files from solr install
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/opt/solr/docs"
        - "/opt/solr/example"
    - name: Create the log directory
      file:
        path: "/opt/solr/server/logs"
        state: directory
        owner: "solr"
        group: "solr"
        mode: "u=rwx,g=rwx,o="
    - name: Download search_api_solr
      get_url:
        url: "https://ftp.drupal.org/files/projects/search_api_solr-7.x-1.x-dev.tar.gz"
        dest: "{{ _run_temp_dir.path }}/search_api_solr.tar.gz"
        mode: "u=rwx,g=rwx,o="
    - name: Expand archive
      unarchive:
        src: "{{ _run_temp_dir.path }}/search_api_solr.tar.gz"
        dest: "{{ _run_temp_dir.path }}/search_api_solr"
        owner: "solr"
        group: "solr"
        mode: "u=rwx,g=rwx,o=r"
        extra_opts:
          - "--strip-components=1"
    - name: Move the search_api_conf directory to /opt
      command: >
        mv {{ _run_temp_dir.path }}/search_api_solr/solr-conf/5.x /opt/search_api_conf
    - name: Download apachesolr
      get_url:
        url: "https://ftp.drupal.org/files/projects/apachesolr-7.x-1.x-dev.tar.gz"
        dest: "{{ _run_temp_dir.path }}/apachesolr.tar.gz"
        mode: "u=rwx,g=rwx,o="
    - name: Expand archive
      unarchive:
        src: "{{ _run_temp_dir.path }}/apachesolr.tar.gz"
        dest: "{{ _run_temp_dir.path }}/apachesolr"
        owner: "solr"
        group: "solr"
        mode: "u=rwx,g=rwx,o=r"
        extra_opts:
          - "--strip-components=1"
    - name: Move the apachesolr_conf directory to /opt
      command: >
        mv {{ _run_temp_dir.path }}/apachesolr/solr-conf/solr-5.x /opt/apachesolr_conf
  handlers:
    - name: delete temp items
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ _run_temp_dir.path }}"
    - name: clear apk cache
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/*"
        - "/var/cache/apk/*"
